# Lab Practice #07

This notebook does not need to be submitted. This is only for you to gain experience and get some practice.

## Numpy Arrays

In [1]:
# Recall from lecture you created numpy arrays.

In [2]:
import numpy as np

In [4]:
arrOne = np.zeros([3,3])
arrTwo = np.ones([3,3])
arrThree = np.identity(3)
arrFour = np.identity(3) + 1
arrFive = arrFour + np.array(range(9)).reshape(3,3)
print(arrOne,"\n") #recall "\n" creates a new line. notice the additional spacing.
print(arrTwo,"\n")
print(arrThree,"\n")
print(arrFour,"\n")
print(arrFive)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]] 

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]] 

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]] 

[[ 2.  1.  1.]
 [ 1.  2.  1.]
 [ 1.  1.  2.]] 

[[  2.   2.   3.]
 [  4.   6.   6.]
 [  7.   8.  10.]]


In [5]:
arrSix = np.array([ [3,7,1,2,9,6,2] ]) # Note the double square brackets.
arrSeven = np.array([ [3],[7],[1],[2],[9],[6],[2] ])
print(arrSix,"\n")
print(arrSeven)

[[3 7 1 2 9 6 2]] 

[[3]
 [7]
 [1]
 [2]
 [9]
 [6]
 [2]]


In [5]:
print(arrSix.shape,"\n")
print(arrSeven.shape)

(1, 7) 

(7, 1)


In [6]:
def myfun(x):
    y = x%2
    return y

In [7]:
print(arrFive,"\n")
zs = np.vectorize(myfun)(arrFive)
print(zs)

[[  2.   2.   3.]
 [  4.   6.   6.]
 [  7.   8.  10.]] 

[[ 0.  0.  1.]
 [ 0.  0.  0.]
 [ 1.  0.  0.]]


### Complete the following exercises.

### Exercise 1:
* Create an array (name it primeArray) containing the first 100 prime numbers.
    You may use the isprime(n) function (positive integer n).
* Reshape the array so that it becomes a 4 row by 25 column array.
* Compute the sum of each row.
* Compute the average of each column.


In [40]:
import numpy as np
# Complete Exercise 1 here.
def isprime(n):
    if n<=1:
        return False
    d = 2
    while d<n:
        if n % d == 0:
            return False
        d += 1
    return True

SOMELIST = []
n = 2
while len(SOMELIST)<100:
    if isprime(n): # This is already a boolean statement.
                   # It returns True or False.
        SOMELIST = SOMELIST + [n]
        #SOMELIST.append(n) # is the same thing
        #SOMELIST.extend([n]) # Also the same thing.
    n += 1
primeArray = np.array([ SOMELIST ]) # HINT.
print(primeArray)
print(primeArray.shape,"\n")
newPrimeArray = primeArray.reshape(4,25)
print(newPrimeArray)
print("\n","\n",np.apply_along_axis(np.sum,1,newPrimeArray),"\n") # ONE
print("\n","\n",np.apply_along_axis(np.average,0,newPrimeArray))  # ZERO

[[  2   3   5   7  11  13  17  19  23  29  31  37  41  43  47  53  59  61
   67  71  73  79  83  89  97 101 103 107 109 113 127 131 137 139 149 151
  157 163 167 173 179 181 191 193 197 199 211 223 227 229 233 239 241 251
  257 263 269 271 277 281 283 293 307 311 313 317 331 337 347 349 353 359
  367 373 379 383 389 397 401 409 419 421 431 433 439 443 449 457 461 463
  467 479 487 491 499 503 509 521 523 541]]
(1, 100) 

[[  2   3   5   7  11  13  17  19  23  29  31  37  41  43  47  53  59  61
   67  71  73  79  83  89  97]
 [101 103 107 109 113 127 131 137 139 149 151 157 163 167 173 179 181 191
  193 197 199 211 223 227 229]
 [233 239 241 251 257 263 269 271 277 281 283 293 307 311 313 317 331 337
  347 349 353 359 367 373 379]
 [383 389 397 401 409 419 421 431 433 439 443 449 457 461 463 467 479 487
  491 499 503 509 521 523 541]]

 
 [ 1060  4057  7601 11415] 


 
 [ 179.75  183.5   187.5   192.    197.5   205.5   209.5   214.5   218.
  224.5   227.    234.    242.    245.5   249. 

In [38]:
print(np.sum(newPrimeArray[0,:]))
print(sum(SOMELIST[0:25]))

1060
1060


### Exercise 2:
* Create a function primeFun(q) that takes in a prime number q and returns $q^{3}-2^{3}$.
* Using np.vectorize apply primeFun to each entry of primeArray.

In [48]:
# Complete Exercise 2 here.
def primeFun(q):
    return (q**3 - 2**3)

# def primeFun(q):
#     return not isprime(q)

zs = np.vectorize(primeFun)(primeArray)

print(zs)


[[        0        19       117       335      1323      2189      4905
       6851     12159     24381     29783     50645     68913     79499
     103815    148869    205371    226973    300755    357903    389009
     493031    571779    704961    912665   1030293   1092719   1225035
    1295021   1442889   2048375   2248083   2571345   2685611   3307941
    3442943   3869885   4330739   4657455   5177709   5735331   5929733
    6967863   7189049   7645365   7880591   9393923  11089559  11697075
   12008981  12649329  13651911  13997513  15813243  16974585  18191439
   19465101  19902503  21253925  22188033  22665179  25153749  28934435
   30080223  30664289  31855005  36264683  38272745  41781915  42508541
   43986969  46268271  49430855  51895109  54439931  56181879  58863861
   62570765  64481193  68417921  73560051  74618453  80062983  81182729
   84604511  86938299  90518841  95443985  97972173  99252839 101847555
  109902231 115501295 118370763 124251491 127263519 131872221 14

### Exercise 3:

In [54]:
# You are given the following two numpy arrays.
arrX = np.array([[1],[7]])
arrY = np.array([[4,-1]])

In [55]:
# What is "arrX.dot(arrY)" doing?
print(arrX.dot(arrY))

[[ 4 -1]
 [28 -7]]


In [56]:
# This is matrix multiplication.
# This is NOT dot product, this is NOT cross product.