# Lab Practice #07

This notebook does not need to be submitted. This is only for you to gain experience and get some practice.

## Numpy Arrays

In [1]:
# Recall from lecture you created numpy arrays.

In [2]:
import numpy as np

In [3]:
arrOne = np.zeros([3,3])
arrTwo = np.ones([3,3])
arrThree = np.identity(3)
arrFour = np.identity(3) + 1
arrFive = arrFour + np.array(range(9)).reshape(3,3)
print(arrOne,"\n") #recall "\n" creates a new line. notice the additional spacing.
print(arrTwo,"\n")
print(arrThree,"\n")
print(arrFour,"\n")
print(arrFive)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]] 

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]] 

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]] 

[[ 2.  1.  1.]
 [ 1.  2.  1.]
 [ 1.  1.  2.]] 

[[  2.   2.   3.]
 [  4.   6.   6.]
 [  7.   8.  10.]]


In [4]:
arrSix = np.array([ [3,7,1,2,9,6,2] ]) # Note the double square brackets.
arrSeven = np.array([ [3],[7],[1],[2],[9],[6],[2] ])
print(arrSix,"\n")
print(arrSeven)

[[3 7 1 2 9 6 2]] 

[[3]
 [7]
 [1]
 [2]
 [9]
 [6]
 [2]]


In [5]:
print(arrSix.shape,"\n")
print(arrSeven.shape)

(1, 7) 

(7, 1)


In [6]:
def myfun(x):
    y = x%2
    return y

In [7]:
print(arrFive,"\n")
zs = np.vectorize(myfun)(arrFive)
print(zs)

[[  2.   2.   3.]
 [  4.   6.   6.]
 [  7.   8.  10.]] 

[[ 0.  0.  1.]
 [ 0.  0.  0.]
 [ 1.  0.  0.]]


### Complete the following exercises.

### Exercise 1:
* Create an array (name it primeArray) containing the first 100 prime numbers. You may use the isprime() function.
* Reshape the array so that it becomes a 4 row by 25 column array.
* Compute the sum of each row.
* Compute the average of each column.


In [8]:
# Complete Exercise 1 here.


### Exercise 2:
* Create a function primeFun(q) that takes in a prime number q and returns $q^{3}-2^{3}$.
* Using np.vectorize apply primeFun to each entry of primeArray.

In [10]:
# Complete Exercise 2 here.


### Exercise 3:

In [45]:
# You are given the following two numpy arrays.
arrX = np.array([[1],[7]])
arrY = np.array([[4,-1]])

In [46]:
# What is "arrX.dot(arrY)" doing?
print(arrX.dot(arrY))

[[ 4 -1]
 [28 -7]]
